name: vens_period_tracker
description: A simple and user-friendly app to help individuals track their menstrual cycles for free.
publish_to: 'none'
version: 1.3.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  provider: ^6.1.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  timezone: ^0.9.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 